### ISSUE TITLE
run gil in Windows fail

### ISSUE THREAD

**Issue by tan-wei** [chronoxor/gil#2]
When gil is run in CMD in Windows, we'll get error message:
```
python: can't open file 'C:\Program': [Errno 2] No such file or directory
```
Python interprater is located in `C:\Program Files (x86)\Python37-32`, so I think we need add quotes in `gil.bat` to prevent this:
```bat
python "%curdir:~0,-1%\gil.py" %*
```

**Comment by chronoxor** [comment]
Fixed in 1.9.0.0
pip3 install gil
