### ISSUE TITLE
SyntaxError: can use starred expression only as assignment target

### ISSUE THREAD

**Issue by gbdimde** [chronoxor/gil#3]
Hello,

I am trying to use gil on a debian 8 machine that comes with python3 3.4.2. Unfortunately running the clone command results in the following error:

`$ gil clone
  File "/usr/local/bin/gil.py", line 285
    params = ["git", "clone", *args, "-b", branch, repo, path]
                                     ^
SyntaxError: can use starred expression only as assignment target`

As far as I have found in the web this syntax requires a python version >3.4.2. Is there any chance to make gil compatible with older python versions, especially 3.4.2?

Thank you
Gert

**Comment by chronoxor** [comment]
Unfortunately no. Backward compatibility to old Python (2.6 or 3.4) is not will be available. Please try to update the Python up to one of the latest version. Recommended is 3.7.x
